#!/bin/sh
sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

polybar mybar &

bspc config window_gap 12
bspc config top_padding 0
bspc config focused_border_color "#A020F0"
bspc config bocused_border_width 1

bspc node -f focused config border_width 2

picom -b &

feh --bg-fill ~/Downloads/pxfuel.jpg

